### ISSUE TITLE
Folder unwritable

### ISSUE THREAD

**Issue by shandshellin** [spritsail/radarr#3]
Hello, when trying to add a root folder from the main page for /tv for example it says it is not writable. If i bin/sh as root i can view the share and i can create folders etc from within the container. Basically i can view and write to the share from both the node where it is mounted and from within the container but not from the actual interface. Any thoughts on what i'm doing wrong here? I'll add that this is a cifs share.

**Comment by shandshellin** [comment]
I have tried add env variables PUID=0 and PGID=0 so it would be ran as root but still no change.

**Comment by shandshellin** [comment]
What user is running in the container?

**Comment by Adam-Ant** [comment]
Hey, the Readme does state this - the user in the container is 901, with a matching group. This can be overridden with the `SUID` & `SGID` env vars. We'd recommend not running it as root if you can help it. Its been a while since I've set up cifs shares, but I think you can set the owner & group as a mount option? Might be the easiest way to sort this.
